#!/usr/bin/env bash
set -e; set -o pipefail;
GIT_WORK_TREE=/home/oblique-bot/app git checkout -f
cp /home/oblique-bot/config.js /home/oblique-bot/app
cd /home/oblique-bot/app && NODE_ENV=production npm install
